# Generated by Django 4.2.7 on 2024-01-30 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infomation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shioriha_Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('link', models.TextField()),
                ('text', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Shioriha_Site',
        ),
    ]
