# Generated by Django 4.2.7 on 2024-01-30 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infomation', '0002_shioriha_videos_delete_shioriha_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shioriha_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('text', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Shioriha_Videos',
        ),
    ]
